In [2]:
import pandas as pd
import numpy as np

In [3]:
lst = [1,2,3,4,5]

arr = np.array(lst)

In [4]:
type(arr)

numpy.ndarray

#### To check the dimentions:

In [5]:
arr.shape

(5,)

In [6]:
lst1 = [4,3,6,2,5]
lst2 = [6,0,3,1,4]
lst3 = [7,9,4,5,1]

# We will give these 3 list as input into numpy array as multiple input

arr_multidimention = np.array([lst1,lst2,lst3])

arr_multidimention

array([[4, 3, 6, 2, 5],
       [6, 0, 3, 1, 4],
       [7, 9, 4, 5, 1]])

In [7]:
arr_multidimention.shape

(3, 5)

> The first one shows the rows and second one shows the columns

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
arr[1]

2

#### arr[starting : ending]

#### -1 means last number

In [10]:
arr[: -1]

array([1, 2, 3, 4])

In [11]:
arr[:: -1]

array([5, 4, 3, 2, 1])

> Reverse the order

In [12]:
arr[1:-1]

array([2, 3, 4])

--------------------

In [13]:
arr

array([1, 2, 3, 4, 5])

### This arr[::-2] says that start from end, ie: 5 take that, then jump 2times, [4 then 3], take 3, jump 2times [2 then 1] take 1.

In [14]:
arr[::-2]

array([5, 3, 1])

### Reshape the array

- The rule of thumb is that the reshape should count to the number of elements in the array

In [15]:
arr_multidimention

array([[4, 3, 6, 2, 5],
       [6, 0, 3, 1, 4],
       [7, 9, 4, 5, 1]])

> Right now there are 5 columns and 3 rows, total 15 elements

In [16]:
arr_multidimention.reshape(5,3)

array([[4, 3, 6],
       [2, 5, 6],
       [0, 3, 1],
       [4, 7, 9],
       [4, 5, 1]])

> Now there are 5 rows and 3 columns

In [17]:
arr_multidimention.reshape(1,15)

array([[4, 3, 6, 2, 5, 6, 0, 3, 1, 4, 7, 9, 4, 5, 1]])

## Generate Array with np.arange

#### 1. It has three values. 
#### 2. np.arange(start, stop(excluded), jump)

In [18]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

> We can reshape it too

In [19]:
np.arange(1,10,1).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Arrays can be multiplied by itself or other array

In [20]:
arr

array([1, 2, 3, 4, 5])

In [21]:
arr * arr  # Multiplied by itself

array([ 1,  4,  9, 16, 25])

In [22]:
arr_multidimention

array([[4, 3, 6, 2, 5],
       [6, 0, 3, 1, 4],
       [7, 9, 4, 5, 1]])

In [23]:
arr * arr_multidimention # multiplied with other

array([[ 4,  6, 18,  8, 25],
       [ 6,  0,  9,  4, 20],
       [ 7, 18, 12, 20,  5]])

#### Some useful functions

### 1. np.Ones

In [24]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 2. np.Zeros

In [25]:
np.zeros((5,14))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### 3. np.RandInt

In [26]:
np.random.randint(10,50)

21

In [27]:
np.random.randint(10,50, 10) # random 10 numbers

array([43, 21, 45, 45, 32, 49, 39, 28, 23, 45])

In [28]:
np.random.random_sample((10,4)) # numbers between 0 and 1

array([[0.87413545, 0.56151623, 0.97185453, 0.59528545],
       [0.9109871 , 0.43096553, 0.87862664, 0.82339516],
       [0.47348737, 0.9894112 , 0.32043987, 0.74544672],
       [0.70782383, 0.47031978, 0.05862768, 0.48293447],
       [0.91671711, 0.29443357, 0.89193571, 0.99772348],
       [0.53701968, 0.64285923, 0.06570864, 0.38401583],
       [0.19582871, 0.86024272, 0.83729534, 0.00561065],
       [0.31819132, 0.63587135, 0.01119437, 0.46960918],
       [0.4605342 , 0.54656998, 0.11018835, 0.3864765 ],
       [0.2918192 , 0.97620838, 0.04889233, 0.89660923]])

## Krish Naik Numpy completed 😊