In [1]:
import pandas as pd
import numpy as np

In [2]:
lst = [1,2,3,4,5]

arr = np.array(lst)

In [3]:
type(arr)

numpy.ndarray

#### To check the dimentions:

In [4]:
arr.shape

(5,)

In [5]:
lst1 = [4,3,6,2,5]
lst2 = [6,0,3,1,4]
lst3 = [7,9,4,5,1]

# We will give these 3 list as input into numpy array as multiple input

arr_multidimention = np.array([lst1,lst2,lst3])

arr_multidimention

array([[4, 3, 6, 2, 5],
       [6, 0, 3, 1, 4],
       [7, 9, 4, 5, 1]])

In [6]:
arr_multidimention.shape

(3, 5)

> The first one shows the rows and second one shows the columns

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr[1]

2

#### arr[starting : ending]

#### -1 means last number

In [9]:
arr[: -1]

array([1, 2, 3, 4])

In [10]:
arr[:: -1]

array([5, 4, 3, 2, 1])

> Reverse the order

In [11]:
arr[1:-1]

array([2, 3, 4])

--------------------

In [13]:
arr

array([1, 2, 3, 4, 5])

### This arr[::-2] says that start from end, ie: 5 take that, then jump 2times, [4 then 3], take 3, jump 2times [2 then 1] take 1.

In [12]:
arr[::-2]

array([5, 3, 1])

### Reshape the array

- The rule of thumb is that the reshape should count to the number of elements in the array

In [14]:
arr_multidimention

array([[4, 3, 6, 2, 5],
       [6, 0, 3, 1, 4],
       [7, 9, 4, 5, 1]])

> Right now there are 5 columns and 3 rows, total 15 elements

In [15]:
arr_multidimention.reshape(5,3)

array([[4, 3, 6],
       [2, 5, 6],
       [0, 3, 1],
       [4, 7, 9],
       [4, 5, 1]])

> Now there are 5 rows and 3 columns

In [18]:
arr_multidimention.reshape(1,15)

array([[4, 3, 6, 2, 5, 6, 0, 3, 1, 4, 7, 9, 4, 5, 1]])

## Generate Array with np.arange

#### 1. It has three values. 
#### 2. np.arange(start, stop(excluded), jump)

In [19]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

> We can reshape it too

In [20]:
np.arange(1,10,1).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Arrays can be multiplied by itself or other array

In [26]:
arr

array([1, 2, 3, 4, 5])

In [27]:
arr * arr  # Multiplied by itself

array([ 1,  4,  9, 16, 25])

In [28]:
arr_multidimention

array([[4, 3, 6, 2, 5],
       [6, 0, 3, 1, 4],
       [7, 9, 4, 5, 1]])

In [30]:
arr * arr_multidimention # multiplied with other

array([[ 4,  6, 18,  8, 25],
       [ 6,  0,  9,  4, 20],
       [ 7, 18, 12, 20,  5]])

#### Some useful functions

### 1. np.Ones

In [22]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 2. np.Zeros

In [23]:
np.zeros((5,14))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### 3. np.RandInt

In [31]:
np.random.randint(10,50)

43

In [34]:
np.random.randint(10,50, 10) # random 10 numbers

array([35, 29, 24, 26, 29, 22, 47, 10, 37, 29])

In [36]:
np.random.random_sample((10,4)) # numbers between 0 and 1

array([[0.01900484, 0.82530526, 0.30531699, 0.55914378],
       [0.45625948, 0.57315141, 0.59437448, 0.04377527],
       [0.19107631, 0.15932408, 0.88558071, 0.68082944],
       [0.91571279, 0.59100571, 0.49038385, 0.89202678],
       [0.80426451, 0.73643071, 0.29508738, 0.39281676],
       [0.37859934, 0.15129631, 0.9873156 , 0.00178298],
       [0.66269513, 0.7136713 , 0.88839044, 0.06431473],
       [0.12808216, 0.06226524, 0.8366467 , 0.58655559],
       [0.75904129, 0.38667383, 0.98262375, 0.62349572],
       [0.67863449, 0.14927393, 0.10107782, 0.86584575]])

## Krish Naik Numpy completed 😊