### Codanics

In [1]:
import pandas as pd
import numpy as np

In [3]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [4]:
a2 = a[np.newaxis, :]
a2

array([[0, 1, 2, 3, 4, 5]])

In [6]:
print(a.shape)
print(a2.shape)

(6,)
(1, 6)


> As can you see that a1 has a sequence of 6 elements whereas the a2 have 1 row and 6 column which shows 2 dimensional array

In [7]:
a3 = a2[np.newaxis, :]
print(a3)

a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

> 3D array

In [25]:
t = np.ones([5,3])
print(t)
print('---------')
y = np.zeros([5,3])
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
---------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### np.ndim gives the dimension of the array

In [17]:
print(f'There are {a2.ndim} dimension in a2 array')

There are 2 dimension in a2 array


### Basic operations

In [26]:
# c = a2 - t
# c