### Codanics 2nd video started 🙂👍

In [1]:
import pandas as pd
import numpy as np

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a2 = a[np.newaxis, :]
a2

array([[0, 1, 2, 3, 4, 5]])

In [4]:
print(a.shape)
print(a2.shape)

(6,)
(1, 6)


> As can you see that a1 has a sequence of 6 elements whereas the a2 have 1 row and 6 column which shows 2 dimensional array

In [5]:
a3 = a2[np.newaxis, :]
print(a3)

a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

> 3D array

In [6]:
t = np.ones([5,3])
print(t)
print('---------')
y = np.zeros([5,3])
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
---------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### np.ndim gives the dimension of the array

In [7]:
print(f'There are {a2.ndim} dimension in a2 array')

There are 2 dimension in a2 array


### Basic operations

In [8]:
# c = a2 - t
# c

## Part 2 video codanics Numpy

In [9]:
import numpy as np

### Empty array:
#### It is called empty as the values are almost near to 0, check the exponent it's saying go back to the power of it

In [10]:
empty = np.empty((4)) # 4 elements in the array
empty

array([0.00000000e+000, 8.61995413e-312, 8.61995413e-312, 8.61995413e-312])

In [11]:
empty = np.empty((6,3)) # 6 rows 3 columns
empty

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [7.56595733e-307, 7.56546842e-307, 8.34441742e-308],
       [1.78022342e-306, 6.23058028e-307, 9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307],
       [1.78021527e-306, 8.34454050e-308, 1.11261027e-306],
       [1.15706896e-306, 1.33512173e-306, 1.42404727e-306]])

In [12]:
empty[1] # 1st row, if we start counting by 0

array([7.56595733e-307, 7.56546842e-307, 8.34441742e-308])

In [13]:
empty[1][1] # 1st row 1st element if start from 0

7.565468422173045e-307

In [14]:
np.arange(23) # normal range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [15]:
np.arange(2 , 23 , 2) # start, end, step size

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [16]:
np.arange(2, 23, 0.344)

array([ 2.   ,  2.344,  2.688,  3.032,  3.376,  3.72 ,  4.064,  4.408,
        4.752,  5.096,  5.44 ,  5.784,  6.128,  6.472,  6.816,  7.16 ,
        7.504,  7.848,  8.192,  8.536,  8.88 ,  9.224,  9.568,  9.912,
       10.256, 10.6  , 10.944, 11.288, 11.632, 11.976, 12.32 , 12.664,
       13.008, 13.352, 13.696, 14.04 , 14.384, 14.728, 15.072, 15.416,
       15.76 , 16.104, 16.448, 16.792, 17.136, 17.48 , 17.824, 18.168,
       18.512, 18.856, 19.2  , 19.544, 19.888, 20.232, 20.576, 20.92 ,
       21.264, 21.608, 21.952, 22.296, 22.64 , 22.984])

### np.Linspace is used to create an array with values that are spaced linearly in a specified interval

In [17]:
np.linspace(0, 20, num=10)   # They are in linear trend and will increase linearly

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [18]:
arr = np.array([2,5,6,0,4,6,1,7,7,8,9,12,3])

In [20]:
arr.sort()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  6,  7,  7,  8,  9, 12])

### 3D array is formed when each array have have atleast two 2D array

In [49]:
example_arr = np.array([
                        [[2,3],[5,6]],
                        
                        [[9,0],[1,5]]
                        
                        ])
print(example_arr)

print('\n')

print(f"The example arr have {example_arr.ndim} dimentions, and have {example_arr.size} elements in it.")

print('\n')

print(f"It's shape is {example_arr.shape}")

print("\n2 row , 2 column, 2 set")

[[[2 3]
  [5 6]]

 [[9 0]
  [1 5]]]


The example arr have 3 dimentions, and have 8 elements in it.


It's shape is (2, 2, 2)

2 row , 2 column, 2 set


### Reshape array

In [55]:
reshape_arr = np.array([0,1,5,7,9,5,4,2])

print(reshape_arr.shape)

reshape_arr.reshape(4,2) # 4 rows 2 columns

(8,)


array([[0, 1],
       [5, 7],
       [9, 5],
       [4, 2]])

### Indexing and slicing


In [56]:
slicing_arr = np.array([3,7,8,8,0,5,2])

slicing_arr

array([3, 7, 8, 8, 0, 5, 2])

In [58]:
slicing_arr[3:6] # start from 3 and ends to 6

array([8, 0, 5])

In [68]:
a = np.array([2,9,0,5,7,8,1,0,3,4])

print(a[a>3]) # prints all the one that are greater than 3

print(a[a <= 1]) 

print(a[(a > 3) &  (a < 9)]) 

print(a[(a > 3) |  (a < 1)]) 

[9 5 7 8 4]
[0 1 0]
[5 7 8 4]
[9 0 5 7 8 0 4]


### Codanics 2nd video completed 😎👍