### Codanics 2nd video started 🙂👍

In [1]:
import pandas as pd
import numpy as np

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a2 = a[np.newaxis, :]
a2

array([[0, 1, 2, 3, 4, 5]])

In [4]:
print(a.shape)
print(a2.shape)

(6,)
(1, 6)


> As can you see that a1 has a sequence of 6 elements whereas the a2 have 1 row and 6 column which shows 2 dimensional array

In [5]:
a3 = a2[np.newaxis, :]
print(a3)

a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

> 3D array

In [6]:
t = np.ones([5,3])
print(t)
print('---------')
y = np.zeros([5,3])
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
---------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### np.ndim gives the dimension of the array

In [7]:
print(f'There are {a2.ndim} dimension in a2 array')

There are 2 dimension in a2 array


### Basic operations

In [8]:
# c = a2 - t
# c

## Part 2 video codanics Numpy

In [9]:
import numpy as np

### Empty array:
#### It is called empty as the values are almost near to 0, check the exponent it's saying go back to the power of it

In [10]:
empty = np.empty((4)) # 4 elements in the array
empty

array([0.00000000e+000, 1.28144316e-311, 1.28144316e-311, 1.28144316e-311])

In [11]:
empty = np.empty((6,3)) # 6 rows 3 columns
empty

array([[1.37962049e-306, 1.24610791e-306, 1.11260959e-306],
       [1.69109959e-306, 9.34603679e-307, 1.42419802e-306],
       [1.78019082e-306, 4.45061456e-308, 1.24612081e-306],
       [1.37962049e-306, 9.34597567e-307, 1.29061821e-306],
       [1.78019625e-306, 1.11255866e-306, 8.90098127e-307],
       [9.34609790e-307, 3.91792279e-317, 0.00000000e+000]])

In [12]:
empty[1] # 1st row, if we start counting by 0

array([1.69109959e-306, 9.34603679e-307, 1.42419802e-306])

In [13]:
empty[1][1] # 1st row 1st element if start from 0

9.346036787346942e-307

In [14]:
np.arange(23) # normal range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [15]:
np.arange(2 , 23 , 2) # start, end, step size

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [16]:
np.arange(2, 23, 0.344)

array([ 2.   ,  2.344,  2.688,  3.032,  3.376,  3.72 ,  4.064,  4.408,
        4.752,  5.096,  5.44 ,  5.784,  6.128,  6.472,  6.816,  7.16 ,
        7.504,  7.848,  8.192,  8.536,  8.88 ,  9.224,  9.568,  9.912,
       10.256, 10.6  , 10.944, 11.288, 11.632, 11.976, 12.32 , 12.664,
       13.008, 13.352, 13.696, 14.04 , 14.384, 14.728, 15.072, 15.416,
       15.76 , 16.104, 16.448, 16.792, 17.136, 17.48 , 17.824, 18.168,
       18.512, 18.856, 19.2  , 19.544, 19.888, 20.232, 20.576, 20.92 ,
       21.264, 21.608, 21.952, 22.296, 22.64 , 22.984])

### np.Linspace is used to create an array with values that are spaced linearly in a specified interval

In [17]:
np.linspace(0, 20, num=10)   # They are in linear trend and will increase linearly

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [18]:
arr = np.array([2,5,6,0,4,6,1,7,7,8,9,12,3])

In [19]:
arr.sort()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  6,  7,  7,  8,  9, 12])

### 3D array is formed when each array have have atleast two 2D array

In [20]:
example_arr = np.array([
                        [[2,3],[5,6]],
                        
                        [[9,0],[1,5]]
                        
                        ])
print(example_arr)

print('\n')

print(f"The example arr have {example_arr.ndim} dimentions, and have {example_arr.size} elements in it.")

print('\n')

print(f"It's shape is {example_arr.shape}")

print("\n2 row , 2 column, 2 set")

[[[2 3]
  [5 6]]

 [[9 0]
  [1 5]]]


The example arr have 3 dimentions, and have 8 elements in it.


It's shape is (2, 2, 2)

2 row , 2 column, 2 set


### Reshape array

In [21]:
reshape_arr = np.array([0,1,5,7,9,5,4,2])

print(reshape_arr.shape)

reshape_arr.reshape(4,2) # 4 rows 2 columns

(8,)


array([[0, 1],
       [5, 7],
       [9, 5],
       [4, 2]])

### Indexing and slicing


In [22]:
slicing_arr = np.array([3,7,8,8,0,5,2])

slicing_arr

array([3, 7, 8, 8, 0, 5, 2])

In [23]:
slicing_arr[3:6] # start from 3 and ends to 6

array([8, 0, 5])

In [24]:
a = np.array([2,9,0,5,7,8,1,0,3,4])

print(a[a>3]) # prints all the one that are greater than 3

print(a[a <= 1]) 

print(a[(a > 3) &  (a < 9)]) 

print(a[(a > 3) |  (a < 1)]) 

[9 5 7 8 4]
[0 1 0]
[5 7 8 4]
[9 0 5 7 8 0 4]


### Codanics 2nd video completed 😎👍

## Matrices in Python

In [25]:
matrix =  np.arange(0, 222, 5)
matrix = matrix.reshape(5,9)
matrix


array([[  0,   5,  10,  15,  20,  25,  30,  35,  40],
       [ 45,  50,  55,  60,  65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110, 115, 120, 125, 130],
       [135, 140, 145, 150, 155, 160, 165, 170, 175],
       [180, 185, 190, 195, 200, 205, 210, 215, 220]])

In [26]:
len(matrix)

5

## We need to slice the matrix, it is simple


In [27]:
c = matrix[0:2,2:5]  # matrix[row(start : end), column (start : end)]
c

array([[10, 15, 20],
       [55, 60, 65]])

----
##### [[  0,   5,  | 10,  15,  20  |,  25,  30,  35,  40],
##### [ 45,  50,   | 55,  60,  65, |  70,  75,  80,  85]]

### For [0:2 , 2:5] so basically it did first select rows from start to 1 as the end is always counted one before so from 0 to 1

### Next for column second part 2:5 it picks from before 2 then ends before 5.

### Hence 10, 15, 20
###       55, 60, 65

In [28]:
matrix.min()

0

In [29]:
matrix.max()

220

In [30]:
matrix.sum()

4950

In [31]:
matrix.min(axis=0) # axis 0 means rows and 1 means column

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40])

In [32]:
matrix.max(axis=1)

array([ 40,  85, 130, 175, 220])

In [33]:

mohsin = np.array([[[2,3],[4,5]],[[8,9],[2,3]]])

# arr3d = np.array([[[2,4],[4,5]], [[5,6],[7,8]]])

In [34]:
mohsin.ndim

3

In [35]:
arr1 = np.arange(0,20,2).reshape(5,2)
arr1

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [36]:
arr2 = np.array([33,50])
arr2

array([33, 50])

In [37]:
arr2 + arr1

array([[33, 52],
       [37, 56],
       [41, 60],
       [45, 64],
       [49, 68]])

> It will add into all

In [38]:
arr2 * arr1

array([[  0, 100],
       [132, 300],
       [264, 500],
       [396, 700],
       [528, 900]])

In [39]:
np.vstack((arr1, arr2)) # it will stack to next

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [33, 50]])

## NumPy: the absolute basics for beginners --Documentation
  

#####  The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [42]:
np.zeros(3) # Create array with zeros in it 

array([0., 0., 0.])

In [49]:
np.ones(5) # Create array with ones

array([1., 1., 1., 1., 1.])

In [50]:
np.empty(10) # An array which initial values are random 

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

#### Create array using range

In [51]:
np.arange(4)

array([0, 1, 2, 3])

In [52]:
np.arange(0, 30, 2) # start at 0 go till 30 and jump 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [55]:
np.linspace(0, 10, num=5) # elements in array are linearly spaced

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [57]:
arr = np.array([9, 2, 6, 2, 7, 0, 6, 4, 2, 1, 5])

arr.sort()
arr

array([0, 1, 2, 2, 2, 4, 5, 6, 6, 7, 9])

In [59]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a,b))


array([1, 2, 3, 4, 5, 6, 7, 8])

# How do you know the shape and size of an array?

In [60]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [62]:
array_example.size # gives number of elements in an array

24

In [64]:
array_example.ndim # provide the dimension of the array

3

In [68]:
array_example.shape # provide the shape 3 row 2 column number of element in each array is 4

(3, 2, 4)

# Can you reshape an array?

In [73]:
new_arr = np.arange(2,50,3)

new_arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [74]:
new_arr.reshape(2,8)

array([[ 2,  5,  8, 11, 14, 17, 20, 23],
       [26, 29, 32, 35, 38, 41, 44, 47]])

In [76]:
ndim1_arr = np.array([1,3,6,9])
ndim1_arr.shape

(4,)

In [77]:
ndim2_arr = ndim1_arr[np.newaxis, :]
ndim2_arr.shape

(1, 4)

### How to reverse an array

In [78]:
arr

array([0, 1, 2, 2, 2, 4, 5, 6, 6, 7, 9])

In [79]:
reversed_arr = np.flip(arr)
reversed_arr

array([9, 7, 6, 6, 5, 4, 2, 2, 2, 1, 0])

# Reshaping and flattening multidimensional arrays

There are two popular ways to flatten an array: **.flatten()** and **.ravel()**. The primary difference between the two is that the new array created using **ravel()** is actually a reference to the parent array (i.e., a “view”). This means that any changes to the new array will affect the parent array as well. Since ravel does not create a copy, it’s memory efficient.

In [81]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
new_flatten_arr = x.flatten() # the flatten function will not have effect on parent array so you need to make another array variable in order to see changes.

new_flatten_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [84]:
y = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

y.ravel()
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])